### ISSUE TITLE
Typo in docs for delete collection

### ISSUE THREAD

**Issue by mtheos** [lupas/firewings#12]
Documentation for  `deleteEntireCollection` references `copyCollection` function

```js
await copyCollection(fireStore, collectionRef, batchSize = 400)

// Firestore = Firestore instance, needed for creating batches
```

https://firewings.netlify.app/functions/firestore/#deleteentirecollection

**Comment by lupas** [comment]
Thanks a lot, appreciate it.

Fixed with https://github.com/lupas/firewings/commit/d33751d5f86d5d6f1f911c0380dcb49e1fcbd761
